language: node_js
node_js:
  - "0.10"
before_install:
  - "git clone https://github.com/meteor/meteor.git ~/meteor"
  - "export PATH=~/meteor/:$PATH"

services:
  - mongodb
script: meteor test --once --driver-package dispatch:mocha-phantomjs
